"""create_initial_accounting_schema

Revision ID: ca18aa2570a9
Revises: 
Create Date: 2026-09-30 11:07:34.866143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca18aa2570a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('started_at < ended_at', name='ck_terms_dates'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index('idx_terms_dates', ['started_at', 'ended_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('student_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('wallet_index', sa.Integer(), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role != 'STUDENT' OR wallet_index IS NOT NULL", name='ck_users_student_wallet'),
    sa.CheckConstraint("role = 'STUDENT' OR wallet_address IS NOT NULL", name='ck_users_council_wallet'),
    sa.CheckConstraint("role IN ('STUDENT', 'TREASURER', 'AUDITOR', 'PRESIDENT')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address'),
    sa.UniqueConstraint('wallet_index')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_no'), ['student_no'], unique=True)

    op.create_table('budgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('planned_amount', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('tx_issue', sa.String(length=66), nullable=True),
    sa.Column('tx_increase', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('planned_amount >= 0', name='ck_budgets_amount'),
    sa.CheckConstraint('version = 1 OR revision_reason IS NOT NULL', name='ck_budgets_revision_reason'),
    sa.CheckConstraint('version >= 1', name='ck_budgets_version'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'category', 'version', name='uq_budgets_term_category_version')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_approved_by', ['approved_by'], unique=False)
        batch_op.create_index('idx_budgets_lookup', ['term_id', 'category', 'version'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.Column('commit_hash', sa.String(length=66), nullable=False),
    sa.Column('minted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('burned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('burned_at IS NULL OR burned_at >= minted_at', name='ck_memberships_burn_date'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('idx_memberships_commit_hash', ['commit_hash'], unique=False)
        batch_op.create_index('idx_memberships_lookup', ['user_id', 'term_id'], unique=False)
        batch_op.create_index('uq_memberships_active_user_term', ['user_id', 'term_id'], unique=True, postgresql_where=sa.text('burned_at IS NULL'))

    op.create_table('snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_balance', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('csv_path', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=66), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bank_balance >= 0', name='ck_snapshots_balance'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshots_term_at', ['term_id', 'snapshot_at'], unique=False)
        batch_op.create_index('idx_snapshots_uploaded_by', ['uploaded_by'], unique=False)

    op.create_table('budget_revision_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_amount', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status != 'REJECTED' OR reject_reason IS NOT NULL", name='ck_budget_rev_reject_reason'),
    sa.CheckConstraint("status = 'PENDING' OR (resolved_by IS NOT NULL AND resolved_at IS NOT NULL)", name='ck_budget_rev_resolved'),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name='ck_budget_rev_status'),
    sa.CheckConstraint('requested_amount >= 0', name='ck_budget_rev_amount'),
    sa.CheckConstraint('resolved_by IS NULL OR requested_by != resolved_by', name='ck_budget_rev_maker_checker'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_revision_requests', schema=None) as batch_op:
        batch_op.create_index('idx_budget_rev_budget', ['budget_id'], unique=False)
        batch_op.create_index('idx_budget_rev_pending', ['term_id', 'status'], unique=False)
        batch_op.create_index('idx_budget_rev_requested_by', ['requested_by'], unique=False)

    op.create_table('entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.BigInteger(), nullable=False),
    sa.Column('receipt_path', sa.String(length=255), nullable=True),
    sa.Column('receipt_hash', sa.String(length=66), nullable=True),
    sa.Column('meta_hash', sa.String(length=66), nullable=True),
    sa.Column('hash_version', sa.Integer(), nullable=False),
    sa.Column('ocr_amount', sa.BigInteger(), nullable=True),
    sa.Column('ocr_approval_no', sa.String(length=50), nullable=True),
    sa.Column('ocr_paid_at', sa.BigInteger(), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=True),
    sa.Column('category_warning', sa.Boolean(), nullable=False),
    sa.Column('warning_ack_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('block_reason', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('rejected_by', sa.BigInteger(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('tx_pending', sa.String(length=66), nullable=True),
    sa.Column('tx_confirm', sa.String(length=66), nullable=True),
    sa.Column('corrects_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('correction_reason', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("block_reason IS NULL OR block_reason IN ('BUDGET_EXCEEDED', 'BUDGET_EXPIRED', 'BUDGET_NOT_FOUND')", name='ck_entries_block_reason'),
    sa.CheckConstraint("correction_reason IS NULL OR correction_reason IN ('INPUT_ERROR', 'RECEIPT_RECHECK', 'REFUND', 'RECLASSIFY')", name='ck_entries_correction_reason'),
    sa.CheckConstraint("kind = 'INCOME' OR budget_id IS NOT NULL", name='ck_entries_expense_budget'),
    sa.CheckConstraint("kind IN ('INCOME', 'EXPENSE')", name='ck_entries_kind'),
    sa.CheckConstraint("ocr_status IS NULL OR ocr_status IN ('MATCH', 'MISMATCH', 'DUPLICATE', 'NO_NUMBER', 'UNREADABLE')", name='ck_entries_ocr_status'),
    sa.CheckConstraint("status != 'REJECTED' OR reject_reason IS NOT NULL", name='ck_entries_reject_reason'),
    sa.CheckConstraint("status IS NULL OR status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'BLOCKED')", name='ck_entries_status'),
    sa.CheckConstraint('amount > 0', name='ck_entries_amount'),
    sa.CheckConstraint('approved_by IS NULL OR created_by != approved_by', name='ck_entries_maker_checker'),
    sa.CheckConstraint('corrects_entry_id IS NULL OR correction_reason IS NOT NULL', name='ck_entries_correct_reason_req'),
    sa.CheckConstraint('corrects_entry_id IS NULL OR corrects_entry_id != id', name='ck_entries_no_self_correct'),
    sa.CheckConstraint('ocr_amount IS NULL OR ocr_amount >= 0', name='ck_entries_ocr_amount'),
    sa.CheckConstraint('rejected_by IS NULL OR created_by != rejected_by', name='ck_entries_rejected_maker'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corrects_entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index('idx_entries_approved_by', ['approved_by'], unique=False)
        batch_op.create_index('idx_entries_budget_id', ['budget_id'], unique=False)
        batch_op.create_index('idx_entries_corrects_entry_id', ['corrects_entry_id'], unique=False)
        batch_op.create_index('idx_entries_created_by', ['created_by'], unique=False)
        batch_op.create_index('idx_entries_dashboard', ['term_id', 'kind', 'status'], unique=False)
        batch_op.create_index('idx_entries_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('idx_entries_rejected_by', ['rejected_by'], unique=False)
        batch_op.create_index('uq_entries_ocr_dup', ['ocr_approval_no', 'ocr_paid_at', 'amount'], unique=True, postgresql_where=sa.text("ocr_approval_no IS NOT NULL AND status != 'REJECTED'"))

    op.create_table('bank_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('tran_date', sa.String(length=10), nullable=False),
    sa.Column('tran_time', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('matched_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('IN', 'OUT')", name='ck_bank_tran_direction'),
    sa.CheckConstraint('amount > 0', name='ck_bank_tran_amount'),
    sa.CheckConstraint('balance_after >= 0', name='ck_bank_tran_balance'),
    sa.ForeignKeyConstraint(['matched_entry_id'], ['entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_bank_tran_snapshot', ['snapshot_id'], unique=False)
        batch_op.create_index('idx_bank_tran_unmatched', ['snapshot_id', 'matched_entry_id'], unique=False)
        batch_op.create_index('uq_bank_tran_matched_entry', ['matched_entry_id'], unique=True, postgresql_where=sa.text('matched_entry_id IS NOT NULL'))

    op.create_table('objections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_raise', sa.String(length=66), nullable=True),
    sa.Column('tx_answer', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status = 'OPEN' OR (answer IS NOT NULL AND answered_by IS NOT NULL AND answered_at IS NOT NULL)", name='ck_objections_answered_state'),
    sa.CheckConstraint("status IN ('OPEN', 'ANSWERED')", name='ck_objections_status'),
    sa.CheckConstraint('answered_at IS NULL OR answered_at >= raised_at', name='ck_objections_dates'),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objections', schema=None) as batch_op:
        batch_op.create_index('idx_objections_entry_id', ['entry_id'], unique=False)
        batch_op.create_index('idx_objections_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objections', schema=None) as batch_op:
        batch_op.drop_index('idx_objections_status')
        batch_op.drop_index('idx_objections_entry_id')

    op.drop_table('objections')
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index('uq_bank_tran_matched_entry', postgresql_where=sa.text('matched_entry_id IS NOT NULL'))
        batch_op.drop_index('idx_bank_tran_unmatched')
        batch_op.drop_index('idx_bank_tran_snapshot')

    op.drop_table('bank_transactions')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index('uq_entries_ocr_dup', postgresql_where=sa.text("ocr_approval_no IS NOT NULL AND status != 'REJECTED'"))
        batch_op.drop_index('idx_entries_rejected_by')
        batch_op.drop_index('idx_entries_occurred_at')
        batch_op.drop_index('idx_entries_dashboard')
        batch_op.drop_index('idx_entries_created_by')
        batch_op.drop_index('idx_entries_corrects_entry_id')
        batch_op.drop_index('idx_entries_budget_id')
        batch_op.drop_index('idx_entries_approved_by')

    op.drop_table('entries')
    with op.batch_alter_table('budget_revision_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_budget_rev_requested_by')
        batch_op.drop_index('idx_budget_rev_pending')
        batch_op.drop_index('idx_budget_rev_budget')

    op.drop_table('budget_revision_requests')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshots_uploaded_by')
        batch_op.drop_index('idx_snapshots_term_at')

    op.drop_table('snapshots')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('uq_memberships_active_user_term', postgresql_where=sa.text('burned_at IS NULL'))
        batch_op.drop_index('idx_memberships_lookup')
        batch_op.drop_index('idx_memberships_commit_hash')

    op.drop_table('memberships')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budgets_lookup')
        batch_op.drop_index('idx_budgets_approved_by')

    op.drop_table('budgets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_no'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index('idx_terms_dates')

    op.drop_table('terms')
    # ### end Alembic commands ###
